version: '3.4'

services:
  fieldbookclient:
    image: fieldbookclient
    build:
      context: src/frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 5173:5173
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "./electron-main.js"]
