#
# Created Date: 10.01.2024 20:38:06
# Author: Julian Hardtung
# 
# Last Modified: 10.01.2024 22:17:27
# Modified By: Julian Hardtung
# 
# Description: Docker compose for full stack fieldbook containerizing
#             TODO: the Dockerfiles will have to be adjusted for production, 
#                   as the images are in dev mode right now
#

services:
  frontend:
    build:
      context: ./src/frontend
    depends_on:
      - backend
    ports:
      - 5173:5173
    develop:
      watch:
        - path: ./src/frontend/package.json
          action: rebuild
        - path: ./src/frontend
          target: /usr/src/app
          action: sync

  backend:
    build:
      context: ./src/backend
    depends_on:
      - mongo
    environment:
      NODE_ENV: production
      DATABASE_URI: mongodb://mongo:27017/fieldbook
    ports:
      - 3000:3000
    develop:
      watch:
        - path: ./src/backend/package.json
          action: rebuild
        - path: ./src/backend
          target: /usr/src/app
          action: sync

  mongo:
    image: mongo:6
    volumes: 
      - database:/data/db
    ports:
      - 27017:27017
      
volumes:
  database:
